# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Ryochan7.DS4Windows
PackageVersion: 3.3.3
InstallerType: nullsoft
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
  - PackageIdentifier: ViGEm.ViGEmBus
  - PackageIdentifier: Nefarius.HidHide
ProductCode: DS4Windows
ReleaseDate: 2023-12-31
Installers:
- Architecture: x64
  InstallerUrl: https://ds4-windows.com/download/ryochan7-ds4windows/?wpdmdl=1927
  InstallerSha256: cf5619bcb51b82e4e1765276e9f67fb1e2d23dff968a653657acf35bafff8bf4
ManifestType: installer
ManifestVersion: 1.6.0

